name: "Todo Micro Service App Infra"

on:
  push:
    branches:
      - 'feature/**'
      - 'main'
      - 'hotfix/**'
  pull_request: 
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  client_id: ${{ secrets.AZURE_CLIENT_ID }}
  tenant_id: ${{ secrets.AZURE_TENANT_ID }}
  subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  working_directory: environment/dev/

jobs:
  terraformInit:
    name: Terraform Init
    runs-on: [self-hosted, todo-microservice-app]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Azure Login using OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ env.client_id }}
          tenant-id: ${{ env.tenant_id }}
          subscription-id: ${{ env.subscription_id }}

      - name: Terraform Init
        id: Init
        run: terraform init
        working-directory: ${{ env.working_directory }}

      - name: Terraform Plan
        id: Plan
        run: terraform plan -var="subscription_id=${{ env.subscription_id }}"
        working-directory: ${{ env.working_directory }}
